version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./docker-compose
            dockerfile: Dockerfile
        image: app-image
        container_name: app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis
            - rabbitmq
    db:
        image: mysql:latest
        container_name: db
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - mysql-db:/var/lib/mysql
        networks:
            - app-network
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/:ro
        networks:
            - app-network
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        logging:
            driver: 'none'
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - app-network
    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        networks:
            - app-network
    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: redis-commander
        restart: always
        ports:
            - "8081:8081"
        environment:
            - REDIS_HOSTS=local:redis:6379
        networks:
            - app-network
    rabbitmq:
        image: rabbitmq:3.10-management
        container_name: rabbitmq
        restart: unless-stopped
        environment:
            - RABBITMQ_DEFAULT_USER=local
            - RABBITMQ_DEFAULT_PASS=local
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - app-network
    worker:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./docker-compose
            dockerfile: Dockerfile
        image: app-image
        container_name: worker
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis
            - rabbitmq
        command: ["sh", "-c", "cd /var/www && php artisan queue:work"]
networks:
    app-network:
        driver: bridge
volumes:
    mysql-db:
    redis-data:
    rabbitmq:
